language: python
python:
    - 3.4
install:
    - pip install -r requirements.txt
    - pip install coveralls
script:
    - pytest --cov=app --cov-report=term-missing
after_success:
    - coveralls



    