language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - pytest  --with-coverage --cover-package=app/api/v1 && coverage report
  - coveralls

after_success:
  - coveralls



    